### ISSUE TITLE
Create a Ruby style guide

### ISSUE THREAD

**Issue by philss** [magnetis/styleguide#21]
Today we have a style guide mostly based on [github style guide](https://github.com/styleguide/ruby). This is quite good, but we need to review and write some new recommendations.
This is a good opportunity to write it here.

**Comment by Lucasosf** [comment]
We could start thinking about https://github.com/bbatsov/ruby-style-guide o/

**Comment by casimiro** [comment]
What are the points that are currently open?

**Comment by philss** [comment]
@Lucasosf actually our maily reference is from this project you mentioned, not Github as I said.
The ideia is to fill our style with points that we consider important, and to review the rules.
I follow conventions that are not described there (in our current style guide).

@casimiro the idea of this issue is to discuss that too. I honestly don't remember all open points.

**Comment by philss** [comment]
Closed by https://github.com/magnetis/styleguide/pull/22.

Thank you, srs!
